---
- name: Security Update and Firewall Policy
  hosts: managed_hosts
  become: yes

  tasks:
    # 1. Update the package list
    - name: Update apt cache
      apt:
        update_cache: yes

    # 2. Upgrade all the existing software into new versions
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    # 3. Install UFW Firewall if it is not installed
    - name: Install UFW (Uncomplicated Firewall)
      apt:
        name: ufw
        state: present

    # 4. Allowing SSH , - critical because need to enable the controlller client version
    - name: Allow SSH (Port 22) - CRITICAL for remote access
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    # 5. Allow port 80 for Web traffic (Apache/Nginx) 
    - name: Allow HTTP (Port 80)
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    # 6. Enable the firewall
    - name: Enable Firewall and set default deny
      ufw:
        state: enabled
        policy: deny
        direction: incoming
